feat: implement an example
casdoor/casdoor-spring-security-react-example pull request #1
Opened 2022-09-08 15:18 UTC by wenxuan70

https://user-images.githubusercontent.com/55948263/189160111-92c3fd61-fc24-4392-95ec-4f3018c09a99.mp4

2022-09-08 17:20 UTC, hsluoyz requested changes

2022-09-08 17:20 UTC, hsluoyz commented on src/main/java/org/casdoor/example/ExampleApplication.java
> +package org.casdoor.example;
Add Casdoor Apache license headers to all source files (.java, ,.js, etc)

2022-09-09 04:57 UTC, wenxuan70 commented
https://user-images.githubusercontent.com/55948263/189271528-ba6184d9-d885-439a-a4b4-53bf50679670.mp4

2022-09-09 05:23 UTC, hsluoyz approved these changes

2022-09-09 05:23 UTC, merged